/*/Objective:
A cab service company wants to enhance its operations by analyzing customer
bookings, driver performance, and trip
details. The company aims to:
- Monitor ongoing and completed bookings.
- Track customer preferences and behavior.
- Evaluate driver efficiency and performance.
- Analyze revenue trends based on fares and trip details.
- Identify operational bottlenecks and areas for improvement.
By structuring and querying the database, stakeholders can make data-driven decisions
to improve the efficiency of the
cab booking system.

Problem Statement:
Customer and Booking Analysis
1. Identify customers who have completed the most bookings. What insights can you
draw about their behavior?
2. Find customers who have canceled more than 30% of their total bookings. What
could be the reason for frequent cancellations?
3. Determine the busiest day of the week for bookings. How can the company optimize
cab availability on peak days?
Driver Performance & Efficiency
1. Identify drivers who have received an average rating below 3.0 in the past three
months. What strategies can be implemented to improve their performance?
2. Find the top 5 drivers who have completed the longest trips in terms of distance.
What does this say about their working patterns?
3. Identify drivers with a high percentage of canceled trips. Could this indicate driver
unreliability?
Revenue & Business Metrics
1. Calculate the total revenue generated by completed bookings in the last 6 months.
How has the revenue trend changed over time?
2. Identify the top 3 most frequently traveled routes based on PickupLocation and
DropoffLocation. Should the company allocate more cabs to these routes?
3. Determine if higher-rated drivers tend to complete more trips and earn higher fares.
Is there a direct correlation between driver ratings and earnings?
Operational Efficiency & Optimization
1. Analyze the average waiting time (difference between booking time and tripstart
time) for different pickup locations. How can this be optimized to reduce delays?
2. Identify the most common reasons for trip cancellations from customer feedback.
What actions can be taken to reduce cancellations?
3. Find out whether shorter trips (low-distance) contribute significantly to revenue.
Should the company encourage more short-distance rides?
Comparative & Predictive Analysis
1. Compare the revenue generated from 'Sedan' and 'SUV' cabs. Should the company
invest more in a particular vehicle type?
2. Predict which customers are likely to stop using the service based on their last
booking date and frequency of rides. How can customer retention be improved?
3. Analyze whether weekend bookings differ significantly from weekday bookings.
Should the company introduce dynamic pricing based on demand?
*/

