/*
Revenue & Business Metrics
1. Calculate the total revenue generated by completed bookings in the last 6 months.
How has the revenue trend changed over time?
2. Identify the top 3 most frequently traveled routes based on PickupLocation and
DropoffLocation. Should the company allocate more cabs to these routes?
3. Determine if higher-rated drivers tend to complete more trips and earn higher fares.
Is there a direct correlation between driver ratings and earnings?
*/
select * from tripdetails;
-- revenue per month 
create view revenue_pm as (
select 
month(endtime) as s_mon,
year(endtime) as s_year,
date_format(EndTime,'%M') as months,
sum(fare) as total_fare_per_month
from tripdetails
group by months
order by s_mon desc
);

select * from revenue_pm;
drop view revenue_pm ;


--
/*
1. Calculate the total revenue generated by completed bookings in the last 6 months.
How has the revenue trend changed over time?
*/

-- to see for last 6 months
with cte_revenue_pm as (
select 
month(endtime) as s_mon,
year(endtime) as s_year,
date_format(EndTime,'%M') as months,
sum(fare) as total_fare_per_month
from tripdetails
group by months
order by s_year,s_mon desc
limit 6)
select 
months,
s_year,
total_fare_per_month,
sum(total_fare_per_month) over (order by s_mon desc ) as cm_revenue_last_6_month
from  cte_revenue_pm ;


/*
1. Total Revenue CalculationThe total revenue generated by completed bookings for last 6 month is {297,649.59}.
2. Monthly Revenue TrendThe table below shows the monthly revenue generated from completed bookings and the running cumulative total for the period.
3. Conclusion: Revenue Trend Analysis : The revenue trend demonstrates exceptional stability and consistency over the five full months analyzed,
										indicating the company has successfully achieved a mature operational rhythm.
No Seasonal Decline: The trend line is essentially flat, showing no signs of seasonal dips or declines through the summer and early fall months.
Highest Performance: The highest full-month revenue was achieved in May 2025 (57,396.60),
                      with September trailing closely behind (57,039.75).
In conclusion, the company has established a robust, highly stable revenue stream that has maintained a consistent monthly value of over (55000) since May.
The focus should now be on incremental strategies to break this plateau and achieve the next level of revenue growth.
*/

/*
2. Identify the top 3 most frequently traveled routes based on PickupLocation and
DropoffLocation. Should the company allocate more cabs to these routes?
*/
-- this are mfp and mfd on indiviual bases
with cte_booking as (
select 
BookingID,
PickupLocation,
DropoffLocation
from bookings
)
,cte_mfp as (
select 
PickupLocation,
count(*) as most_pick,
row_number() over(order by count(*) desc) as rnp
from cte_booking
group by pickuplocation
)
,cte_mfd as (
select 
dropoffLocation,
count(*) as most_drop,
row_number() over(order by count(*) desc) as rnd
from cte_booking
group by dropofflocation
)
select 
mfp.pickuplocation,
mfp.most_pick,
mfd.dropofflocation,
mfd.most_drop
from cte_mfp as mfp
join cte_mfd as mfd
on mfp.rnp = mfd.rnd 
order by rnp
limit 3 ;

-- top 3 routes 

select 
concat(coalesce(pickuplocation,"")," - ",coalesce(dropofflocation,"")) as route,
count(*) as rides_on_route
from bookings
group by route
order by rides_on_route desc
limit 3 ;

/*
The company should strategically allocate more cab availability to these routes,
but the focus should be on optimizing cab positioning and staging rather than simply increasing the overall number of cars.
The high frequency means these routes are critical to revenue and customer experience.

Strategic Allocation Recommendations:
	1)Demand Positioning at Origins: The company should implement a system to ensure cab supply is highest at the origin locations of these top routes 
									 before peak demand strikes.Market Staging: Ensure a queue or staging area is maintained near the Market area,
                                     especially during high-traffic times (e.g., evenings, weekends) to service the (Market - Hotel) route.
                                     
	2)Minimize Latency for Time-Sensitive Routes: The (Hotel - Airport) route is often time-critical. 
												  The priority must be to reduce wait times at hotels, 
                                                  perhaps through partnerships or by offering incentives for drivers to take short waiting periods at large hotels.
	3)Optimize Return Trips: Cabs that drop off passengers at the Airport from the (Hotel - Airport) route should be automatically prioritized for the next high-demand leg,
                             such as the (Airport - Mall) route. This minimizes "dead mileage" and matches supply with immediate, proven demand.

Conclusion: These routes are vital arteries for the business.
			Allocating more resources to them is essential, not just by having more drivers,
            but by leveraging technology to direct existing drivers to the high-demand pickup points {Market}, {Hotel} and {Airport} precisely when the trips are needed. 
*/


/*
3. Determine if higher-rated drivers tend to complete more trips and earn higher fares.
Is there a direct correlation between driver ratings and earnings?
*/

-- taking driver rating on bases of past 3 months 

select * from ps2;
with cte_ps3c as (
select
driverid, 
name,
ang_driver_rating as avg_driver_rating
from ps2
group by name 
order by avg_driver_rating desc
limit 5
)
,cte_fare_and_count as (
select
driverid, 
round(avg(fare),2) as avg_fare,
round(avg(distancekm),2) as avg_dist,
count(*) as no_of_rides
from bookings 
group by driverid )
select 
ps3.driverid,
ps3.name,
fc.avg_fare,
fc.avg_dist,
fc.no_of_rides,
round(ps3.avg_driver_rating,2) as last_3_M_driver_rating,
round(fc.no_of_rides*fc.avg_fare,2) as earning
from cte_ps3c as ps3
join cte_fare_and_count as fc 
using(driverid);

/*
conclusion : there no direct relationship between both as such

Strategic Recommendation
 The company should treat Recent Rating as an Reward Indicator and Total Earnings/Rides as a Lifetime Value Indicator.
  1) Reward Recent Improvement: Use the 3-month rating to quickly reward or course-correct drivers for their immediate service quality.

  2)Incentivize High-LTV Drivers: Focus resource allocation on drivers with a high lifetime contribution 
                                  who are also maintaining high recent quality—by giving them priority access to the top 3 high-demand routes.
*/
